ossf/scorecard-webapp

- .gitignore
- Dockerfile
- LICENSE
- Makefile
- go.mod
- k8s.yaml
- main.go
Sets up a basic framework for developing scorecard.dev webapp.
> 🌱 Skeleton to setup scorecard.dev webapp

- Dockerfile
- Makefile
> 🐛 Fix Dockerfile

- SECURITY.md
> ✨ Add a Security policy

- .github/workflows/scorecards-analysis.yml
Dependabot did not update the version comment.
> Update version in workflow comment

- .github/workflows/codeql-analysis.yml
Adding sha's to codeql workflow
> Fixing scorecard alerts

- scorecards-site/package.json
- scorecards-site/yarn.lock
Signed-off-by: Mark Dunbavan <mdunbavan@gmail.com>
> fixed vulnerabilities

- scorecards-site/app.prod.yaml
- scorecards-site/app.staging.yaml
- scorecards-site/cloudbuild.prod.yaml
- scorecards-site/cloudbuild.staging.yaml
> 🌱 Add staging and prod deployments to scorecard-site

- scorecards-site/cloudbuild.prod.yaml
- scorecards-site/cloudbuild.staging.yaml
> 🐛 Fix typo in CloudBuild config

- scorecards-site/content/home.md
- scorecards-site/modules/Header/Header.vue
- scorecards-site/nuxt.config.js
> 🐛 Fix UI/Content issues

- .github/workflows/depsreview.yml
Included dependency reviews check.
> :seedling: Included dependency reviews check

- scorecards-site/nuxt.config.js
Signed-off-by: Mark Dunbavan <mdunbavan@gmail.com>
> fix goat counter script load issue

- scorecards-site/components/global/CodeGroup.vue
- scorecards-site/components/global/Sidebar.vue
- scorecards-site/content/home.md
- scorecards-site/modules/Header/Header.js
For issue #75 with the added bug of sidebar not loading
Signed-off-by: Mark Dunbavan <mdunbavan@gmail.com>
> bump fix for sidebar not loading

- .gitignore
- app/testdata/workflow-invalid-execaction.yml
- app/testdata/workflow-invalid-missing-runson.yml
- app/testdata/workflow-invalid-missing-scorecard.yml
- app/testdata/workflow-invalid-multiple-labels.yml
- app/testdata/workflow-invalid-nil-steps.yml
- app/verify_workflow.go
- app/verify_workflow_test.go
- I wanted to understand the code and realized the best way to learn was to write tests.
> Included additional tests for validate workflow

- CODE_OF_CONDUCT.md
- README.md
Context: https://www.netlify.com/legal/open-source-policy/
This allows us to be deployed on Netlify for free.
> 🌱 Meet the requirements for Netlify's OSS plan

- README.md
Follow-up to https://github.com/ossf/scorecard-webapp/pull/160.
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> README: Prefer non-generated name for Netlify site badge

- README.md
- scorecards-site/README.md
Add documentation on the site and API.
> 📖 Add documentation

- .github/workflows/scorecards-analysis.yml
> 🌱 Update scorecard-action to v2:alpha

- app/generated/restapi/configure_scorecard.go
Some static files weren't being rendered in Swagger static page
> 🐛 Fix bug in static page rendering

- .github/workflows/main.yml
- Fixed the go version from 1.17 to 1.18
> Fix - Go version

- app/server/verify_workflow.go
Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
Fix for https://github.com/ossf/scorecard-action/issues/910
> 🐛 Add exception for step-security/harden-runner

- app/server/testdata/workflow-valid-e2e.yml
- app/server/testdata/workflow-valid.yml
- app/server/verify_workflow.go
Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
Remove `action-create-issue` as accepted action.
> 🌱 Remove `create-issue` as acceptable step

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
Signed-off-by: David Korczynski <david@adalogics.com>
> Create CIFuzz Github action

- .golangci.yml
> Clean up - golanglint ci cleanup

- app/server/post_results.go
- Included code comments on the rekor validation.
> :book: Included comments on the rekor validation

- app/server/verify_workflow.go
Signed-off-by: laurentsimon <laurentsimon@google.com>
See https://github.com/ossf/scorecard-action/issues/910#issuecomment-1355288592
> Add ubuntu-22 as trusted runner

- app/server/verify_workflow.go
Signed-off-by: laurentsimon <laurentsimon@google.com>
> feat: better logging for runner labels

- app/server/post_results_test.go
- Included unit tests for getcertPool
> Included unit tests for certpool

- scorecards-site/content/home.md
- Fixed the link to the "Dangerous Workflow" section
- Fixed the descriptions for "Dangerous Workflow" and "Branch Protection" by switching them
> Fix content for "Source risk assessment" table (#396)

- scorecards-site/pages/index.vue
Temporary link to survey added at top of page.
> 🌱 Add survey link

- app/server/verify_workflow.go
Fixes https://github.com/ossf/scorecard-action/issues/1381
> :bug: add support for ubuntu-24.04 runner
