ossf/scorecard-webapp

- k8s.yaml
The webapp is now exposed at 34.68.26.31:443. Will ask LF to point https://scorecard.dev to this IP.
> ✨ Expose the Scorecard webapp on external IP

- k8s.yaml
Adds support for HTTPS queries to the scorecard-webapp. Tested at https://securityscorecards.dev
> ✨ Add Google-managed SSL cert

- .github/workflows/scorecards-analysis.yml
Temporarily disable PAT and use `GITHUB_TOKEN` instead.
> 🌱 Use `GITHUB_TOKEN` instead of PAT

- k8s.yaml
Setup https://api.securityscorecards.dev. This will be used by @rohankh532 to return `POST` and `GET` Scorecard results.
How it will work:
- Scorecard GitHub Action will make the call `POST https://api.securityscorecards.dev` (with the right payload) to verify and store the result.
- A publicly accessible endpoint can call `GET https://api.securityscorecards.dev/{platform}/{org}/{name}` to get the latest stored Scorecard result. E.g `GET https://api.securityscorecards.dev/github.com/ossf/scorecard`.
- Use the `GET` API in `sheilds.io`.
@rohankh532 fyi.
> 🌱 Setup api.securityscorecards.dev

- scorecards-site/.github/dependabot.yml
Changing the reviewer for dependabot PRs to be scorecard-maintainers.
> 🌱 Dependabot PRs reviewed by scorecard-maintainers

- scorecards-site/nuxt.config.js
Potential fix for #75 
- adding ssr to the app might stop the app from waiting for the client to load before the script and creating the JSOn code error on refresh. We are basically loading it all in one go with this strategy and not expecting the client-side to do the heavy lifting for us.
Signed-off-by: Mark Dunbavan <mdunbavan@gmail.com>
> PR for issue #75

- app/errors.go
- app/get_results.go
- app/testdata/workflow-valid-e2e.yml
- app/verify_workflow.go
- app/verify_workflow_test.go
Fixes e2e test failures in scorecard-action:
- e2e tests use steps which are different from the prod steps, so added an exception for them. Fixes ossf/scorecard-action#455, fixes ossf/scorecard-action#456, fixes ossf/scorecard-action#457, fixes ossf/scorecard-action#458, fixes ossf/scorecard-action#459, fixes ossf/scorecard-action#460
- Improve http error handling. Fixes  #116.
> 🐛 Fix scorecard-action e2e test breakages

- app/post_results.go
It is not guaranteed that the response from Rekor API - `map{ "uuid": "tlogEntry" }` will match the uuid that was requested due to some extra sharding bits being attached. So removing that logic.
> 🐛 Fix bug in uuid lookup

- .github/workflows/scorecards-analysis.yml
There was no `id-token` permission defined for GitHub workflow which Scorecard badge requires.
> 🐛 Fix the job permission for Scorecard action

- app/get_results.go
- app/get_results_test.go
- app/post_results.go
This PR records per-commit info during POST request and updates the GET request to support `?commit=` URL param. The PR also adds support to lookup cron results as a backup mechanism when scorecard-action results are unavailable.
> ✨ Record and return per-commit results in API

- netlify.toml
The build command should be generating the files for Nuxt to use. So updating from `build` -> `generate`. @mdunbavan fyi
> 🐛 Update netlify.toml

- app/post_results.go
- app/post_results_test.go
- Created unit tests for `extractCertInfo`
- Updated the error to be a standard error so that it is easier to test.
- The `extractCertInfo` - 100% code coverage. 
> :seedling: Unit tests for extract cert info

- app/generated/restapi/static/swagger-initializer.js
API url was pointing to the staging site instead of prod.
> 🐛 Fix wrong URL

- scorecards-site/nuxt.config.js
- scorecards-site/pages/index.vue
Updates the site title to `OpenSSF Scorecard` instead of `OSSF Security Scorecards`.
> 🌱 Update the site title

- app/generated/restapi/configure_scorecard.go
- app/generated/restapi/server.go
Partially addresses #206 
Originally proposed in https://github.com/ossf/scorecard/pull/2251, but the JSON marshalling/unmarshalling in the webapp would overrule any change made there.
It's introduced as a flag, where the default is no indentation / pretty printing. This matches the current behavior.
I'm unfamiliar with CloudRun, so if it's hard to specify in the production deployment a static value can be used.
```
./scorecard-webapp -h
Usage:
scorecard-server [OPTIONS]
OpenSSF Scorecard API
API to interact with a project's published Scorecard result
--cleanup-timeout duration     grace period for which to wait before killing idle connections (default 10s)
--graceful-timeout duration    grace period for which to wait before shutting down the server (default 15s)
--host string …
```
> 🌱 Format API JSON output

- CODE_OF_CONDUCT.md
Update the placeholder text with the correct email address (as confirmed on the OpenSSF Slack).
Signed-off-by: Caleb Brown <github@calebbrown.id.au>
> Add the contact to the code of conduct.

- app/generated/models/scorecard_check.go
- app/generated/models/scorecard_result.go
- app/generated/restapi/embedded_spec.go
- openapi.yaml
Changed the ordering and properties of fields so that the JSON served by the webapp will match the JSON output from `scorecard` as defined here (including order of subtypes)
https://github.com/ossf/scorecard/blob/46c6fe700cdc10a780f3c867b36b6810e1986cb0/pkg/json.go#L81-L88
This helps when hashing the file in order to find the file in the Rekor transparency log.
All changes were made to `openapi.yaml` and the other files were generated via `make swagger`.
> :seedling: Match JSON output produced by Scorecard

- .github/workflows/cifuzz.yml
The runs for this workflow have been failing for a while:
https://github.com/ossf/scorecard-webapp/actions/workflows/cifuzz.yml
Going to try a bump to the latest commit (there are no releases, so dependabot doesn't update for us)
> :seedling: Bump oss-fuzz actions.

- .github/workflows/main.yml
- .golangci.yml
golangci-lint-action had a release which changed some behavior in depguard and is causing the linter to fail now:
https://github.com/ossf/scorecard-webapp/actions/runs/5152614093/jobs/9287923800
We don't appear to be using depguard (we have no `.depguard.yml` file or similar), so might as well disable it.
> :seedling: Disable depguard linter and pin golangci-lint-action.

- app/server/post_results.go
- app/server/verify_workflow.go
Should resolve https://github.com/ossf/scorecard-action/issues/1150 once a new webapp release is cut. The underlying logic always existed for POST requests, but the implementation wasn't working due to a `%v` instead of a `%w` here:
https://github.com/ossf/scorecard-webapp/blob/9c2f66d5f6ff56ca4a4ac2fba6ec8dcc5379d31c/app/server/post_results.go#L233-L236
After testing locally, I received the following response to the issue reporter's POST data:
```
{
"code": 400,
"message": "workflow verification failed: workflow contains global env vars or defaults, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."
}
```
> :bug: Surface workflow verification errors with doc link

- app/generated/models/scorecard_check.go
- app/generated/models/scorecard_result.go
- app/generated/restapi/embedded_spec.go
- openapi.yaml
Reverts ossf/scorecard-webapp#377
The openAPI spec are being used in a way that releasing this change would be a breaking change, both inside the Go ecosystem and outside.
https://github.com/jetstack/tally/blob/54a465ebd3d5c729d0c5529c5125b517e8e4f0b4/go.mod#L12
https://github.com/NodeSecure/ossf-scorecard-sdk/blob/ff5f8d5b5d698760c373aeff84fd0b99602dd9b3/src/index.ts#L19-L21
I don't think the re-ordering parts are a breaking change, but without the `metadata` changes, the SHAs (of the API output and the JSON uploaded to the rekor transparency log) won't match the original scorecard output so I'm just reverting the whole PR.
I still think the change is worth doing eventually, once we figure out how to make (small) breaking changes to the API.
> Revert ":seedling: Match JSON output produced by Scorecard"

- app/server/verify_workflow.go
Follow up of #389. The original PR didn't wrap the error in the new verification error which was introduced in #408.
So when a workflow was rejected for having an imposter commit, the user got this message:
> error processing signature: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it.
This PR wraps the imposter commit message so the error is surfaced. The error message also now includes the ref which triggered the warning, so the user doesn't need to guess/check.
> error processing signature: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: imposter commit: deadbeef088af7c0dc8046f3ac9a8f4148492a95 does not belong to step-security/harden-runner, see …
> :bug: Enhance and surface imposter commit errors.

- .github/dependabot.yml
- Reduces docker update dependency to weekly.
- Quotes the reviewers value to see if the team actually gets assigned to review dependabot PRs
> :seedling: Cleanup dependabot config

- .github/dependabot.yml
Indentation was invalid during #166.
Dependabot complains only when pushed to main (https://github.com/ossf/scorecard-webapp/runs/15991713628). Which  is a known issue: https://github.com/dependabot/dependabot-core/issues/4605
I've validated the indentation locally with a YAML linter.
> :seedling: Fix dependabot config indentation.

- app/generated/client/badge/badge_client.go
- app/generated/restapi/doc.go
- app/generated/restapi/embedded_spec.go
- app/generated/restapi/operations/scorecard_api.go
- openapi.yaml
We were previously saying the `Content-Type` header for the badge was `application/json` which was causing issues for proxies (e.g. `go-camo` which is used by pypi).
E.g: https://pypi.org/project/numpy shows a broken OpenSSF Scorecard badge.
> :bug: Specify badge endpoints returns content-type image/svg+xml

- app/server/verify_workflow.go
- app/server/verify_workflow_test.go
This is a quick fix for the problem, and a proper fix can be investigated later. More details provided in https://www.github.com/github/codeql-action/issues/2040
Fixes #517
> :bug: also check releases/v2 branch for github/codeql-action

- .github/workflows/main.yml
1. Go 1.18 isn't supported
2. Should fix the issues in the latest group of dependabot PRs: (e.g #522). At least it does locally, testing with `act`
> :seedling: use Go 1.21 in CI

- .github/dependabot.yml
these dependencies are released at the same time and generate 8+ PRs. After grouping it should just be one PR going forward.
See #575 through #585
https://github.com/ossf/scorecard-webapp/issues?q=go-openapi+is%3Aclosed+author%3Aapp%2Fdependabot+created%3A2024-03-10..2024-03-12
> :seedling: group dependabot updates for go-openapi dependencies

- app/server/post_results_e2e_test.go
- app/server/verify_workflow.go
Support suggested version of `actions/upload-artifact` so we can update the scorecard starter workflow.
See https://github.com/actions/starter-workflows/pull/2348#discussion_r1536247210
I also added an e2e test so we can verify certain commits remain accepted if we change our validation strategy. This manual list of fallbacks isn't ideal.
> :bug: add fallback lookup for `actions/upload-artifact` `v3/node20` branch

- scorecards-site/static/viewer/index.html
Update scorecard-viewer display. 
Also update URL from [securityscorecards.dev](securityscorecards.dev) -> [scorecard.dev](scorecard.dev).
Fixes #441.
> 🌱 viewer: display scorecard version, API results URL

- app/server/verify_workflow.go
- app/server/verify_workflow_test.go
The release process for that action creates a time window where commits exist in releases/v3 before they get merged back into main. This led to imposter commit timing issues when users were merging updates.
Fixes https://github.com/ossf/scorecard-action/issues/1367
> :bug: check github/codeql-action releases/v3 branch explicitly.

- app/server/testdata/workflow-valid-e2e-ghcr.yml
- app/server/verify_workflow.go
- app/server/verify_workflow_test.go
Follow up of #707, and adds a test (which I should have done the first time). The test is identical to the existing workflow but with the gcr.io changed to the ghcr.io image.
Fixes https://github.com/ossf/scorecard-action/issues/1468
> allow the ghcr image when finding scorecard job

- .github/workflows/main.yml
By default, the action uses `latest`, which can cause new issues to appear independent of any code changes in this repository.
This issue is blocking #740 for example, because v1.64 was released
> specify golangci-lint version explicitly in lint workflow

- app/server/badge.go
Related to https://github.com/ossf/scorecard/issues/4591
While the redirect was working locally with curl, I suspect the space may be causing issues with GitHub's camo proxy. This suspicion is due to a test README I did which directly linked failed to render:
But using the plus seemed to render.
> fix GitHub markdown rendering by removing space from badge style

- app/server/verify_workflow.go
E.g. https://github.com/open-telemetry/opentelemetry-java-contrib/blob/b3a3b2cd17e2d2d30589872bb535ede9029844ec/.github/workflows/ossf-scorecard.yml#L26-L33
> Allow `actions/create-github-app-token` for generating the necessary token from a GitHub App
